// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexJnvcZQudwe515EpDaP4EW4uJkUWo1o',
    appId: '1:17664284236:web:91a663968570b61613c6e9',
    messagingSenderId: '17664284236',
    projectId: 'email-f2430',
    authDomain: 'email-f2430.firebaseapp.com',
    storageBucket: 'email-f2430.firebasestorage.app',
    measurementId: 'G-3EXYKJ0KXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xqgdIwSPlJCZfzHgq0vIsfk0W1Fm56k',
    appId: '1:17664284236:android:ef0b85a00f41e8ba13c6e9',
    messagingSenderId: '17664284236',
    projectId: 'email-f2430',
    storageBucket: 'email-f2430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABghQLVXE-dbl_3F2jwTBU6XtV5oEUHag',
    appId: '1:17664284236:ios:820236666200a27f13c6e9',
    messagingSenderId: '17664284236',
    projectId: 'email-f2430',
    storageBucket: 'email-f2430.firebasestorage.app',
    androidClientId: '17664284236-1mv4tiodsluoqqnr5ur709n40jmdpebi.apps.googleusercontent.com',
    iosClientId: '17664284236-52ffe2l10plufuhi7ajr3cj6mnb4f03a.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesrev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABghQLVXE-dbl_3F2jwTBU6XtV5oEUHag',
    appId: '1:17664284236:ios:820236666200a27f13c6e9',
    messagingSenderId: '17664284236',
    projectId: 'email-f2430',
    storageBucket: 'email-f2430.firebasestorage.app',
    androidClientId: '17664284236-1mv4tiodsluoqqnr5ur709n40jmdpebi.apps.googleusercontent.com',
    iosClientId: '17664284236-52ffe2l10plufuhi7ajr3cj6mnb4f03a.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesrev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbZihERMDD4qemvLRh4ai_kERtInNDSag',
    appId: '1:17664284236:web:b2d071c4214ddf9113c6e9',
    messagingSenderId: '17664284236',
    projectId: 'email-f2430',
    authDomain: 'email-f2430.firebaseapp.com',
    storageBucket: 'email-f2430.firebasestorage.app',
    measurementId: 'G-1J45W98ETZ',
  );

}